<table class="battle-report">
	<tr>
		<td>&nbsp;</td>
		<th colspan="4" class="battle-report-entity battle-report-end-of-section">Defenders</th>
		<th colspan="4" class="battle-report-entity battle-report-end-of-section">Attackers</th>
		<th colspan="4" class="battle-report-entity">Your ships</th>
	</tr>
	<tr>
		<th>Ship</th>
		<th class="battle-report-stat-heading">Total</th>
		<th class="battle-report-stat-heading">Killed</th>
		<th class="battle-report-stat-heading">Frozen</th>
		<th class="battle-report-stat-heading battle-report-end-of-section">Stolen</th>

		<th class="battle-report-stat-heading">Total</th>
		<th class="battle-report-stat-heading">Killed</th>
		<th class="battle-report-stat-heading">Frozen</th>
		<th class="battle-report-stat-heading battle-report-end-of-section">Stolen</th>
		
		<th class="battle-report-stat-heading">Total</th>
		<th class="battle-report-stat-heading">Killed</th>
		<th class="battle-report-stat-heading">Frozen</th>
		<th class="battle-report-stat-heading">Stolen</th>
	</tr><tr>
	<th>EMP&nbsp;freezing&nbsp;ship</th>
	<td class="stat">800</td>
	<td class="stat">276</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">400</td>
	<td class="stat">108</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
</tr><tr>
	<th>Attacking&nbsp;ship&nbsp;1</th>
	<td class="stat">700</td>
	<td class="stat">241</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">500</td>
	<td class="stat">136</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
</tr><tr>
	<th>Attacking&nbsp;ship&nbsp;2</th>
	<td class="stat">2,000</td>
	<td class="stat">800</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">1,200</td>

	<td class="stat">3,000</td>
	<td class="stat">558</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">2,442</td>

	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
</tr><tr>
	<th>Attacking&nbsp;ship&nbsp;3</th>
	<td class="stat">1,500</td>
	<td class="stat">600</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">900</td>

	<td class="stat">1,750</td>
	<td class="stat">325</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">1,425</td>

	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
</tr><tr>
	<th>Stealing&nbsp;ship</th>
	<td class="stat">5,000</td>
	<td class="stat">217</td>
	<td class="stat">43</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">4,000</td>
	<td class="stat">71</td>
	<td class="stat">44</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
</tr><tr>
	<th>Salvage&nbsp;ship</th>
	<td class="stat">1,000</td>
	<td class="stat">43</td>
	<td class="stat">8</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">4,000</td>
	<td class="stat">71</td>
	<td class="stat">44</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
</tr><tr>
	<th>Asteroid&nbsp;stealing&nbsp;ship</th>
	<td class="stat">500</td>
	<td class="stat">172</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">2,000</td>
	<td class="stat">544</td>
	<td class="stat">0</td>
	<td class="stat battle-report-end-of-section">0</td>

	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
	<td class="stat">0</td>
</tr>	<tr>
		<th>Totals</th>
		<th class="stat">11,500</th>
		<th class="stat">2,349</th>
		<th class="stat">51</th>
		<th class="stat battle-report-end-of-section">2,100</th>

		<th class="stat">15,650</th>
		<th class="stat">1,813</th>
		<th class="stat">88</th>
		<th class="stat battle-report-end-of-section">3,867</th>
		
		<th class="stat">0</th>
		<th class="stat">0</th>
		<th class="stat">0</th>
		<th class="stat">0</th>
	</tr>
	<tr>
		<th>&nbsp;</th>
		<th colspan="4" class="battle-report-resource-stat battle-report-end-of-section">
			Salvaged 382,600 P and 91,900 S.
		</th>
		<th colspan="4" class="battle-report-resource-stat battle-report-end-of-section">
			Defender had 100 asteroids, 10 stolen.
		</td>
		<th colspan="4" class="battle-report-resource-stat">
			You stole 0 asteroids.
		</td>
	</tr>
</table>