<h2>MMOG: The Beginning</h2>

<div class="intro">
	<p>This is an open source game. <a href="https://github.com/chrisjhill/PHP-Battlescript">Follow it on GitHub here.</a></p>

	<p>
		<input type="button" name="battle_submit" id="battle_submit" value="Start the battle sequence" />
	</p>
</div>

<hr />

<div id="battle_output">
	<h3>Battle output</h3>

	<div class="container">
		<p id="battle_output_introduction">
			Click the button above<br />
			to see the output here
		</p>
	</div>
</div>